### ISSUE TITLE
TODO List 

### ISSUE THREAD

**Issue by rcdevgames** [imamjnn/RNBoilerplate#2]
### Overview
React Native ini akan di buat untuk menjadi base projek apapun dengan dukungan react-redux dan mode hooks dan berbagai macam plugin untuk memudahkan proses development.

- [ ] Install react-redux
- [ ] Install react-form-hooks
- [ ] Install vector-icon dengan fontawesome pro
- [ ] Install local database sqlite
- [ ] Install datetime picker
- [ ] Install crashlytics (Firebase)
